#FROM openjdk:jre-alpine
FROM openjdk:8-jre-alpine

ADD target/acmeair-authservice-java-3.3-thorntail.jar /opt/thorntail.jar

ENV JAEGER_SERVICE_NAME=jaeger-service
ENV JAEGER_AGENT_HOST=jaeger
ENV JAEGER_REPORTER_LOG_SPANS=false
ENV JAEGER_SAMPLER_TYPE=const
ENV JAEGER_SAMPLER_PARAM=1

COPY src/main/liberty/config/resources/security/key.p12 /opt/key.p12

ENV KEYSTORE_LOCATION=/opt/key.p12

EXPOSE 9080
ENTRYPOINT ["java", "-Dhttp.keepalive=true", "-Dhttp.maxConnections=100", "-jar","/opt/thorntail.jar", "-Djava.net.preferIPv4Stack=true", "-Dthorntail.context.path=/auth" ,"-Dthorntail.http.port=9080"]
