FROM openjdk:11-jre-slim
WORKDIR /helidon

# Copy the binary built in the 1st stage
COPY target/acmeair-authservice-java.jar ./helidon.jar
COPY target/libs ./libs
COPY src/main/liberty/config/resources/security/key.p12 /helidon/key.p12
ENV KEYSTORE_LOCATION=/helidon/key.p12

CMD ["java","-Dhttp.keepalive=true", "-Dhttp.maxConnections=100","-jar", "helidon.jar"]

EXPOSE 9080
